package de.raphaelgoetz.betterbuild.utils

import org.bukkit.Material

enum class Terracotta(val material: Material) {
    WHITE(Material.WHITE_GLAZED_TERRACOTTA),
    ORANGE(Material.ORANGE_GLAZED_TERRACOTTA),
    MAGENTA(Material.MAGENTA_GLAZED_TERRACOTTA),
    LIGHT_BLUE(Material.LIGHT_BLUE_GLAZED_TERRACOTTA),
    YELLOW(Material.YELLOW_GLAZED_TERRACOTTA),
    LIME(Material.LIME_GLAZED_TERRACOTTA),
    PINK(Material.PINK_GLAZED_TERRACOTTA),
    GRAY(Material.GRAY_GLAZED_TERRACOTTA),
    LIGHT_GRAY(Material.LIGHT_GRAY_GLAZED_TERRACOTTA),
    CYAN(Material.CYAN_GLAZED_TERRACOTTA),
    PURPLE(Material.PURPLE_GLAZED_TERRACOTTA),
    BLUE(Material.BLUE_GLAZED_TERRACOTTA),
    BROWN(Material.BROWN_GLAZED_TERRACOTTA),
    GREEN(Material.GREEN_GLAZED_TERRACOTTA),
    RED(Material.RED_GLAZED_TERRACOTTA),
    BLACK(Material.BLACK_GLAZED_TERRACOTTA);
}