name: BetterBuild
version: '${version}'
main: de.raphaelgoetz.betterbuild.BetterBuild
api-version: '1.20'
author: 'Konfuzius'
website: 'https://uroria.com'
description: "A useful Minecraft building tool, that manages the server on which you build."

commands:
  gm:
    description: "Updates the player game-mode!"
  build:
    description: "Toggle Build-Mode. When activated players can interact with the world!"
  clip:
    description: "Toggle Clip-Mode. When activated you get put into spectator mode when colliding with blocks!"
  fly:
    description: "Sets the fly-speed of a player. Only values from 0-10."
  walk:
    description: "Sets the walk-speed of a player. Only values from 0-10."
  back:
    description: "Teleports a player to the last known location after switching worlds."
  world:
    description: "Creates and deletes words."
  physics:
    description: "Toggle Physics-Mode. When activated physics of a world will be at minecraft's-default."